Repository cyberbotics/webots-snap, pull requests merged in 2020-12, with the labels that each got.

#27 Improve upload of GitHub action artifacts
  .github/workflows/snap-creation.yml
Labels: enhancement, test creation

#28 Update README.md
  README.md
Labels: invalid

#29 Update snap-creation.yml
  .github/workflows/snap-creation.yml
Labels: bug
